
service: sample-service

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs6.10

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: /hello
          method: get